config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"

  # Rotas dos Posts
  get "/posts", to: "posts#index"
  get "/posts/filter/:filter", to: "posts#filter", as: "posts_filter"
  get "/posts/search", to: "posts#search", as: "posts_search"
  delete "/posts/:id", to: "posts#destroy"
  get "/posts/new", to: "posts#new"
  get "/posts/edit/:id", to: "posts#edit", as: "post_edit"
  post "/posts", to: "posts#create"
  get "/posts/:id", to: "posts#show", as: "post"
  patch "/posts/:id", to: "posts#update"
  put "/posts/:id", to: "posts#update"

  # Rotas dos Usuários
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]
  get "users/:id/send-email", to: "users#email", as: "email"
  # Rotas das sessions
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    is_impressionable
    belongs_to :user
    
    scope :bad, ->{ where('rating <= ?', 3) }
    scope :good, ->{ where('rating > ?', 3) }
    scope :your_ratings,-> (test) { where('user_id = ?', test) }
end

app/models/user.rb
class User < ApplicationRecord

    has_many :posts
    has_secure_password

    validates :username, presence: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  helper_method :current_user

   def current_user
     return unless session[:user_id]
     @current_user ||= User.find(session[:user_id])
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :update, :destroy, :edit]
  impressionist :actions=>[:index, :show]
  ONLY_LETTERS_REGEX = /^[\w\s.-]+$/i

  # GET /posts
  def index
    @posts = Post.all().order("rating")
    
    respond_to do |format|
    format.html { render :index}
    format.json { render json: @posts}
    end
  end

  def search
    @search_term = params[:search]
    @posts = Post.where("title LIKE lower(?)", "%#{@search_term}%")
    render :index
  end

  def filter
    respond_to do |format|

      if params[:filter].blank?
        redirect_to posts_path
      elsif params[:filter] == 'good'
        @posts = Post.good.order("rating")
        format.html { render :index}
        format.json { render json: @posts}
      elsif params[:filter] == 'bad'
        @posts = Post.bad.order("rating")
        format.html { render :index}
        format.json { render json: @posts}
      elsif params[:filter] == 'my-ratings'
        @posts = Post.your_ratings(current_user.id).order("rating")
        format.html { render :index}
        format.json { render json: @posts}
      else
        @posts = Post.all().order("rating")
        format.html { redirect_to posts_path}
        format.json { render json: @posts}
      end
    end
  end

  # GET /posts/:id
  def show
    respond_to do |format|
      impressionist(@post)
      format.html { render :show}
      format.json { render json: @post}
      end
    end
  
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      
      if @post.title.blank? || @post.description.blank? || !@post.title.match(ONLY_LETTERS_REGEX)
        format.html { render :new, notice: 'Incorrect fields are not accepted.'  }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      elsif @post.save
        format.json { render json: @post, status: :created }
        format.html { redirect_to @post, notice: 'Test was successfully created.' }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.html { render :new}
      end
    end
  end

  # PATCH/PUT /posts/:id
  def update
    respond_to do |format|
      if post_params[:title].blank? || post_params[:description].blank? || !@post.update(post_params)
        format.html { render :edit, notice: 'Invalid fields, please fill it correctly'  }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      else
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok}
      end
    end
  end
   
  # DELETE /posts/:id
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def new
    @post = Post.new
  end

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def post_params
  params.require(:post).permit(:title, :description, :rating, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def render_not_found(exception)
    render json: { error: exception.message }, status: :not_found
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])

    if !!@user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      message =  "Something haven't worked well, make sure you filled everything correctly"
      redirect_to login_path, notice: message
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

  def email
    UserMailer.welcome_email(current_user).deliver_now
    redirect_to root_path, notice: 'An email has been sent!'
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
    
    def current_username
        @current_username ||= User.find_by_id(session[:user_id]).username if !!session[:user_id]
    end

    def current_email
        @current_email ||= User.find_by_id(session[:user_id]).email if !!session[:user_id]
    end

    def admin?
        current_user.admin if !!session[:user_id]
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Posts', posts_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse " id="navbarNav">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_username %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'See your account', user_url(session[:user_id]), class: "dropdown-item"%>
          <%= link_to 'Logout', logout_path, method: :destroy , class: "dropdown-item"%>
        </div>
      </li>
    <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Sign In', login_url, class: "dropdown-item"%>
          <%= link_to 'Sing up', new_user_url, class: "dropdown-item"%>
        </div>
      </li>
    <% end %> 
    </ul>
    <%= form_tag(posts_search_url, method: :get, class: "form-inline my-2 my-lg-0") do %>
      <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control mr-sm-2" %>
      <%= button_tag "Search", :class => "btn btn-outline-success my-2 my-sm-0", :name => nil  %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <%= render 'layouts/header'%>
    
    <div class="container">
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-group">
<%= form_with(model: post, local: true) do |form| %>

  <div class="field">
    <%= form.label "Title (Only letters or numbers)" %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :post_rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>p
<% end %>
</div>

app/views/posts/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mb-2 w-100">
<h1><% if logged_in? %>
      Hi, <%= current_user.username %>!
    <% else %>
      Hi, anonimous!
    <% end %>
     here is a list of the Posts!
</h1>


    
    <div class="dropdown float-l">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filters
        </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <% if request.original_url.include? 'good' or request.original_url.include? 'bad' or request.original_url.include? 'your-ratings' %>
                    <%= link_to 'Remove filter', posts_path, class: 'dropdown-item'%>
                    <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to 'Bad ratings', posts_filter_url('bad'), class: 'dropdown-item' %>
                <%= link_to 'Good ratings', posts_filter_url('good'), class: 'dropdown-item' %>
                <%= link_to 'Your ratings', posts_filter_url('my-ratings'), class: 'dropdown-item' if logged_in? %>
            </div>
        </div>
    <%= link_to 'New Post', posts_new_path, class: "btn btn-dark ml-3 mr-2" if logged_in? %>
    <%= link_to 'Clean search', posts_path, class: "btn btn-dark" if !@search_term.blank? %>
    </div>

    

    
<div class="row">
<% @posts.each do |post|%>
        <div class="col-6">
            <div class="card mb-4 ml-1 mr-1">
                <div class="card-body">
                <p class="card-subtitle text-muted pos-abs">Author: <%= @author = User.find_by_id(post.user_id).username %></p>
                <p class="card-subtitle text-muted pos-abs2"> viewed <%= post.impressionist_count %> times</p>
                    <h4 class="card-title"><%= post.title %></h4>
                    <h5 class="card-subtitle mb-2 text-muted" ><%= post.rating %> stars</h5>
                    <p class="card-text"><%= post.description %></p>
                    
                    
                    <%= link_to 'Show', post %>
                    <%= link_to 'Edit', post_edit_url(post.id) if admin? || @author == current_username %>
                    <%= link_to 'Delete', post, method: :delete if admin? || @author == current_username %>
                </div>
            </div>
        </div>
<% end %>
</div>
    

    
 

app/views/posts/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<h1>Teste</h1>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @post.rating %>
</p>

<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<div>
    <h1>New users</h1>

    <%= form_for @user do |f|%>
        <%= f.label :username %>
        <%= f.text_field :username %><br>
        <%= f.label :email %>
        <%= f.text_field :email %><br>
        <%= f.label :password %>
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>
        <%= submit_tag 'Create account' %>
    <% end %>
</div>

app/views/users/show.html.erb
<div>
   <p id="notice"><%= notice %></p>

    <p>
    <strong>Username:</strong>
    <%= @user.username %>
    </p>

    <p>
    <strong>Email:</strong>
    <%= @user.email %>
    </p>

    <p>
    Hi, <%= @user.username %>! I'm here to help you :)
    </p>


    <%= link_to 'Back', posts_path %> | <%= link_to 'Send test email', email_url %>
 
</div>